config/routes.rb
Datagen::Application.routes.draw do
  resources :towns

  resources :cities

  resources :prefectures

  resources :given_names

  resources :family_names

  get "/help/:action" => "help#:action"

  root :to => 'top#index'

  match ':controller(/:action(/:id))'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/given_name.rb
# -*- coding: utf-8 -*-
class GivenName < ActiveRecord::Base
end

app/controllers/given_names_controller.rb
# -*- coding: utf-8 -*-

class GivenNamesController < ApplicationController
  # GET /given_names
  # GET /given_names.xml
  def index
    @given_names = GivenName.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @given_names }
    end
  end

  # GET /given_names/1
  # GET /given_names/1.xml
  def show
    @given_name = GivenName.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @given_name }
    end
  end

  # GET /given_names/new
  # GET /given_names/new.xml
  def new
    @given_name = GivenName.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @given_name }
    end
  end

  # GET /given_names/1/edit
  def edit
    @given_name = GivenName.find(params[:id])
  end

  # POST /given_names
  # POST /given_names.xml
  def create
    @given_name = GivenName.new(params[:given_name])

    respond_to do |format|
      if @given_name.save
        flash[:notice] = 'GivenName was successfully created.'
        format.html { redirect_to(@given_name) }
        format.xml  { render :xml => @given_name, :status => :created, :location => @given_name }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @given_name.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /given_names/1
  # PUT /given_names/1.xml
  def update
    @given_name = GivenName.find(params[:id])

    respond_to do |format|
      if @given_name.update_attributes(params[:given_name])
        flash[:notice] = 'GivenName was successfully updated.'
        format.html { redirect_to(@given_name) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @given_name.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /given_names/1
  # DELETE /given_names/1.xml
  def destroy
    @given_name = GivenName.find(params[:id])
    @given_name.destroy

    respond_to do |format|
      format.html { redirect_to(given_names_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/given_names_helper.rb
module GivenNamesHelper
end

app/views/given_names/edit.html.erb
<h1>Editing given_name</h1>

<% form_for(@given_name) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :pronunciation %><br />
    <%= f.text_field :pronunciation %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @given_name %> |
<%= link_to 'Back', given_names_path %>

app/views/given_names/index.html.erb
<h1>Listing given_names</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Pronunciation</th>
    <th>Created by</th>
    <th>Updated by</th>
  </tr>

<% @given_names.each do |given_name| %>
  <tr>
    <td><%=h given_name.name %></td>
    <td><%=h given_name.pronunciation %></td>
    <td><%=h given_name.created_by %></td>
    <td><%=h given_name.updated_by %></td>
    <td><%= link_to 'Show', given_name %></td>
    <td><%= link_to 'Edit', edit_given_name_path(given_name) %></td>
    <td><%= link_to 'Destroy', given_name, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New given_name', new_given_name_path %>

app/views/given_names/new.html.erb
<h1>New given_name</h1>

<% form_for(@given_name) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :pronunciation %><br />
    <%= f.text_field :pronunciation %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', given_names_path %>

app/views/given_names/show.html.erb
<p>
  <b>Name:</b>
  <%=h @given_name.name %>
</p>

<p>
  <b>Pronunciation:</b>
  <%=h @given_name.pronunciation %>
</p>

<p>
  <b>Created by:</b>
  <%=h @given_name.created_by %>
</p>

<p>
  <b>Updated by:</b>
  <%=h @given_name.updated_by %>
</p>


<%= link_to 'Edit', edit_given_name_path(@given_name) %> |
<%= link_to 'Back', given_names_path %>