config/routes.rb
Datagen::Application.routes.draw do
  resources :towns

  resources :cities

  resources :prefectures

  resources :given_names

  resources :family_names

  get "/help/:action" => "help#:action"

  root :to => 'top#index'

  match ':controller(/:action(/:id))'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/prefecture.rb
# -*- coding: utf-8 -*-
class Prefecture < ActiveRecord::Base
  set_primary_key 'pref_code'
  has_many :cities, :foreign_key => 'pref_code'
  has_many :towns,  :foreign_key => 'pref_code'
end

app/controllers/prefectures_controller.rb
# -*- coding: utf-8 -*-

class PrefecturesController < ApplicationController
  # GET /prefectures
  # GET /prefectures.xml
  def index
    @prefectures = Prefecture.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @prefectures }
    end
  end

  # GET /prefectures/1
  # GET /prefectures/1.xml
  def show
    @prefecture = Prefecture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @prefecture }
    end
  end

  # GET /prefectures/new
  # GET /prefectures/new.xml
  def new
    @prefecture = Prefecture.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @prefecture }
    end
  end

  # GET /prefectures/1/edit
  def edit
    @prefecture = Prefecture.find(params[:id])
  end

  # POST /prefectures
  # POST /prefectures.xml
  def create
    @prefecture = Prefecture.new(params[:prefecture])

    respond_to do |format|
      if @prefecture.save
        flash[:notice] = 'Prefecture was successfully created.'
        format.html { redirect_to(@prefecture) }
        format.xml  { render :xml => @prefecture, :status => :created, :location => @prefecture }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prefecture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /prefectures/1
  # PUT /prefectures/1.xml
  def update
    @prefecture = Prefecture.find(params[:id])

    respond_to do |format|
      if @prefecture.update_attributes(params[:prefecture])
        flash[:notice] = 'Prefecture was successfully updated.'
        format.html { redirect_to(@prefecture) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prefecture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /prefectures/1
  # DELETE /prefectures/1.xml
  def destroy
    @prefecture = Prefecture.find(params[:id])
    @prefecture.destroy

    respond_to do |format|
      format.html { redirect_to(prefectures_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/views/prefectures/edit.html.erb
<h1>Editing prefecture</h1>

<% form_for(@prefecture) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :pref_code %><br />
    <%= f.text_field :pref_code %>
  </p>
  <p>
    <%= f.label :pref_code_iso %><br />
    <%= f.text_field :pref_code_iso %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :pronounce %><br />
    <%= f.text_field :pronounce %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @prefecture %> |
<%= link_to 'Back', prefectures_path %>

app/views/prefectures/index.html.erb
<h1>Listing prefectures</h1>

<table>
  <tr>
    <th>Pref code</th>
    <th>Pref code iso</th>
    <th>Name</th>
    <th>Pronounce</th>
    <th>Created by</th>
    <th>Updated by</th>
  </tr>

<% @prefectures.each do |prefecture| %>
  <tr>
    <td><%=h prefecture.pref_code %></td>
    <td><%=h prefecture.pref_code_iso %></td>
    <td><%=h prefecture.name %></td>
    <td><%=h prefecture.pronounce %></td>
    <td><%=h prefecture.created_by %></td>
    <td><%=h prefecture.updated_by %></td>
    <td><%= link_to 'Show', prefecture %></td>
    <td><%= link_to 'Edit', edit_prefecture_path(prefecture) %></td>
    <td><%= link_to 'Destroy', prefecture, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New prefecture', new_prefecture_path %>

app/views/prefectures/new.html.erb
<h1>New prefecture</h1>

<% form_for(@prefecture) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :pref_code %><br />
    <%= f.text_field :pref_code %>
  </p>
  <p>
    <%= f.label :pref_code_iso %><br />
    <%= f.text_field :pref_code_iso %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :pronounce %><br />
    <%= f.text_field :pronounce %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', prefectures_path %>

app/views/prefectures/show.html.erb
<p>
  <b>Pref code:</b>
  <%=h @prefecture.pref_code %>
</p>

<p>
  <b>Pref code iso:</b>
  <%=h @prefecture.pref_code_iso %>
</p>

<p>
  <b>Name:</b>
  <%=h @prefecture.name %>
</p>

<p>
  <b>Pronounce:</b>
  <%=h @prefecture.pronounce %>
</p>

<p>
  <b>Created by:</b>
  <%=h @prefecture.created_by %>
</p>

<p>
  <b>Updated by:</b>
  <%=h @prefecture.updated_by %>
</p>


<%= link_to 'Edit', edit_prefecture_path(@prefecture) %> |
<%= link_to 'Back', prefectures_path %>