config/routes.rb
Datagen::Application.routes.draw do
  resources :towns

  resources :cities

  resources :prefectures

  resources :given_names

  resources :family_names

  get "/help/:action" => "help#:action"

  root :to => 'top#index'

  match ':controller(/:action(/:id))'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/city.rb
# -*- coding: utf-8 -*-
class City < ActiveRecord::Base
  set_primary_key 'city_code'
  has_many :towns, :foreign_key => "city_code"
end

app/controllers/cities_controller.rb
# -*- coding: utf-8 -*-

class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.xml
  def index
    @cities = City.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.xml
  def show
    @city = City.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.xml
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.xml
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        flash[:notice] = 'City was successfully created.'
        format.html { redirect_to(@city) }
        format.xml  { render :xml => @city, :status => :created, :location => @city }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @city.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.xml
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        flash[:notice] = 'City was successfully updated.'
        format.html { redirect_to(@city) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @city.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.xml
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to(cities_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<% form_for(@city) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :pref_code %><br />
    <%= f.text_field :pref_code %>
  </p>
  <p>
    <%= f.label :city_code %><br />
    <%= f.text_field :city_code %>
  </p>
  <p>
    <%= f.label :city_code_cd %><br />
    <%= f.text_field :city_code_cd %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :pronunciation %><br />
    <%= f.text_field :pronunciation %>
  </p>
  <p>
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <tr>
    <th>Pref code</th>
    <th>City code</th>
    <th>City code cd</th>
    <th>Name</th>
    <th>Pronunciation</th>
    <th>Telephone</th>
    <th>Created by</th>
    <th>Updated by</th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%=h city.pref_code %></td>
    <td><%=h city.city_code %></td>
    <td><%=h city.city_code_cd %></td>
    <td><%=h city.name %></td>
    <td><%=h city.pronunciation %></td>
    <td><%=h city.telephone %></td>
    <td><%=h city.created_by %></td>
    <td><%=h city.updated_by %></td>
    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'Destroy', city, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New city', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<% form_for(@city) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :pref_code %><br />
    <%= f.text_field :pref_code %>
  </p>
  <p>
    <%= f.label :city_code %><br />
    <%= f.text_field :city_code %>
  </p>
  <p>
    <%= f.label :city_code_cd %><br />
    <%= f.text_field :city_code_cd %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :pronunciation %><br />
    <%= f.text_field :pronunciation %>
  </p>
  <p>
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p>
  <b>Pref code:</b>
  <%=h @city.pref_code %>
</p>

<p>
  <b>City code:</b>
  <%=h @city.city_code %>
</p>

<p>
  <b>City code cd:</b>
  <%=h @city.city_code_cd %>
</p>

<p>
  <b>Name:</b>
  <%=h @city.name %>
</p>

<p>
  <b>Pronunciation:</b>
  <%=h @city.pronunciation %>
</p>

<p>
  <b>Telephone:</b>
  <%=h @city.telephone %>
</p>

<p>
  <b>Created by:</b>
  <%=h @city.created_by %>
</p>

<p>
  <b>Updated by:</b>
  <%=h @city.updated_by %>
</p>


<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>