config/routes.rb
Datagen::Application.routes.draw do
  resources :towns

  resources :cities

  resources :prefectures

  resources :given_names

  resources :family_names

  get "/help/:action" => "help#:action"

  root :to => 'top#index'

  match ':controller(/:action(/:id))'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/town.rb
# -*- coding: utf-8 -*-
class Town < ActiveRecord::Base
  belongs_to :prefecture, :foreign_key => "pref_code"
  belongs_to :city, :foreign_key => "city_code"

  def generate_banchi
    @banchi = ''
    cho_me = sprintf("%d",rand(9)+1)
    ban_chi = sprintf("%d",rand(20)+1)
    goh = sprintf("%d",rand(50)+1)

    mode = rand(2)+1
    tmp = Hash.new
    case mode
      when 1
        han = cho_me + '-' + ban_chi + '-' + goh
        zen = han.tr("0-9\-","０-９－")
        tmp[:name] = zen
        tmp[:pronunciation] = zen
      when 2
        han = cho_me + '-' + ban_chi
        zen = han.tr("0-9\-","０-９－")
        tmp[:name] = zen
        tmp[:pronunciation] = zen
    end
    @banchi = tmp
  end

  def banchi
    return @banchi
  end
end

app/controllers/towns_controller.rb
# -*- coding: utf-8 -*-

class TownsController < ApplicationController
  # GET /towns
  # GET /towns.xml
  def index
    @towns = Town.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @towns }
    end
  end

  # GET /towns/1
  # GET /towns/1.xml
  def show
    @town = Town.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @town }
    end
  end

  # GET /towns/new
  # GET /towns/new.xml
  def new
    @town = Town.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @town }
    end
  end

  # GET /towns/1/edit
  def edit
    @town = Town.find(params[:id])
  end

  # POST /towns
  # POST /towns.xml
  def create
    @town = Town.new(params[:town])

    respond_to do |format|
      if @town.save
        flash[:notice] = 'Town was successfully created.'
        format.html { redirect_to(@town) }
        format.xml  { render :xml => @town, :status => :created, :location => @town }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /towns/1
  # PUT /towns/1.xml
  def update
    @town = Town.find(params[:id])

    respond_to do |format|
      if @town.update_attributes(params[:town])
        flash[:notice] = 'Town was successfully updated.'
        format.html { redirect_to(@town) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.xml
  def destroy
    @town = Town.find(params[:id])
    @town.destroy

    respond_to do |format|
      format.html { redirect_to(towns_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/towns/edit.html.erb
<h1>Editing town</h1>

<% form_for(@town) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :search_id %><br />
    <%= f.text_field :search_id %>
  </p>
  <p>
    <%= f.label :pref_code %><br />
    <%= f.text_field :pref_code %>
  </p>
  <p>
    <%= f.label :city_code %><br />
    <%= f.text_field :city_code %>
  </p>
  <p>
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :pronunciation %><br />
    <%= f.text_field :pronunciation %>
  </p>
  <p>
    <%= f.label :st1 %><br />
    <%= f.text_field :st1 %>
  </p>
  <p>
    <%= f.label :st2 %><br />
    <%= f.text_field :st2 %>
  </p>
  <p>
    <%= f.label :st3 %><br />
    <%= f.text_field :st3 %>
  </p>
  <p>
    <%= f.label :st4 %><br />
    <%= f.text_field :st4 %>
  </p>
  <p>
    <%= f.label :st5 %><br />
    <%= f.text_field :st5 %>
  </p>
  <p>
    <%= f.label :st6 %><br />
    <%= f.text_field :st6 %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

app/views/towns/index.html.erb
<h1>Listing towns</h1>

<table>
  <tr>
    <th>Search</th>
    <th>Pref code</th>
    <th>City code</th>
    <th>Zip code</th>
    <th>Name</th>
    <th>Pronunciation</th>
    <th>St1</th>
    <th>St2</th>
    <th>St3</th>
    <th>St4</th>
    <th>St5</th>
    <th>St6</th>
    <th>Created by</th>
    <th>Updated by</th>
  </tr>

<% @towns.each do |town| %>
  <tr>
    <td><%=h town.search_id %></td>
    <td><%=h town.pref_code %></td>
    <td><%=h town.city_code %></td>
    <td><%=h town.zip_code %></td>
    <td><%=h town.name %></td>
    <td><%=h town.pronunciation %></td>
    <td><%=h town.st1 %></td>
    <td><%=h town.st2 %></td>
    <td><%=h town.st3 %></td>
    <td><%=h town.st4 %></td>
    <td><%=h town.st5 %></td>
    <td><%=h town.st6 %></td>
    <td><%=h town.created_by %></td>
    <td><%=h town.updated_by %></td>
    <td><%= link_to 'Show', town %></td>
    <td><%= link_to 'Edit', edit_town_path(town) %></td>
    <td><%= link_to 'Destroy', town, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New town', new_town_path %>

app/views/towns/new.html.erb
<h1>New town</h1>

<% form_for(@town) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :search_id %><br />
    <%= f.text_field :search_id %>
  </p>
  <p>
    <%= f.label :pref_code %><br />
    <%= f.text_field :pref_code %>
  </p>
  <p>
    <%= f.label :city_code %><br />
    <%= f.text_field :city_code %>
  </p>
  <p>
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :pronunciation %><br />
    <%= f.text_field :pronunciation %>
  </p>
  <p>
    <%= f.label :st1 %><br />
    <%= f.text_field :st1 %>
  </p>
  <p>
    <%= f.label :st2 %><br />
    <%= f.text_field :st2 %>
  </p>
  <p>
    <%= f.label :st3 %><br />
    <%= f.text_field :st3 %>
  </p>
  <p>
    <%= f.label :st4 %><br />
    <%= f.text_field :st4 %>
  </p>
  <p>
    <%= f.label :st5 %><br />
    <%= f.text_field :st5 %>
  </p>
  <p>
    <%= f.label :st6 %><br />
    <%= f.text_field :st6 %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', towns_path %>

app/views/towns/show.html.erb
<p>
  <b>Search:</b>
  <%=h @town.search_id %>
</p>

<p>
  <b>Pref code:</b>
  <%=h @town.pref_code %>
</p>

<p>
  <b>City code:</b>
  <%=h @town.city_code %>
</p>

<p>
  <b>Zip code:</b>
  <%=h @town.zip_code %>
</p>

<p>
  <b>Name:</b>
  <%=h @town.name %>
</p>

<p>
  <b>Pronunciation:</b>
  <%=h @town.pronunciation %>
</p>

<p>
  <b>St1:</b>
  <%=h @town.st1 %>
</p>

<p>
  <b>St2:</b>
  <%=h @town.st2 %>
</p>

<p>
  <b>St3:</b>
  <%=h @town.st3 %>
</p>

<p>
  <b>St4:</b>
  <%=h @town.st4 %>
</p>

<p>
  <b>St5:</b>
  <%=h @town.st5 %>
</p>

<p>
  <b>St6:</b>
  <%=h @town.st6 %>
</p>

<p>
  <b>Created by:</b>
  <%=h @town.created_by %>
</p>

<p>
  <b>Updated by:</b>
  <%=h @town.updated_by %>
</p>


<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>